function pce = contElemF(lenM, xLen, ceMdl)
% contElemF find the force generated by CE
% pce = contElemF(idM, lenM, xLen, ceMdl) Given the id of the muscle and 
% the current length of that muscle returns the force generated due to the 
% contractile element's model
%
% lenM	:	current length vector for the muscles
% xLen	:	vector that keeps the (possible) length of the muscles to be used
%           for the model
% ceMdl	:	model for the contractile element


% return the first element that is greater&equal than the current length of
% the muscle in order to find the corresponding force generated by the CE.
pce = zeros(8,1);
k = length(lenM);
for i = 1:k
    n = find(xLen(i,:) >= lenM(i), 1);
    if isempty(n)
        n = size(xLen, 2);
    end
    pce(i) = ceMdl(i, n);    % find the force on CE
end
