function pce = FbyFV(vCE, fMdl, vMdl)
% contElemF find the force generated by CE from FV curve
%  vce = contElemFV(fM, fMdl, vMdl) Given the id of the muscle and
% the current force of that muscle returns the velocity generated due to the
% contractile element's model
%
% fM	:	current force on the contractile element
% fMdl	:	vector that keeps the (possible) forces of the CE to be used
%           for the model
% vMdl	:	model for the contractile element FV curve
global lM0;

% return the first element that is greater&equal than the current length of
% the muscle in order to find the corresponding force generated by the CE.
pce = zeros(8,1);

for i = 1:8
    if vCE < -10*lM0
        pce(i) = 0;
    else
        n = find(vMdl(i,:) >= vCE(i), 1);
        pce(i) = fMdl(i, n);    % find the force on CE
    end
end
pce = pce.*(lM0*1000);
